### ISSUE TITLE
US010- As a club head, I want the ability to add social media managers and club members to help manage our club's online presence.

### ISSUE THREAD

**Issue by ishreya09** [ishreya09/Campus-Compass#10]
- [x] Assignment Interface (F001): Create a user-friendly interface that allows club heads to select registered users as social media managers and club members for their club.

- [x] Privileges and Access (F002): Allow social media managers to create announcements to manage the social account.

**Comment by Mystery510** [comment]
@DarkKnightSgh do the testing
