### ISSUE TITLE
US014-As a user, I want to view important announcements and updates on college events, including club events.

### ISSUE THREAD

**Issue by ishreya09** [ishreya09/Campus-Compass#14]
Announcement Display (F001): Display announcements and updates to users. This feature involves:

- [x] Announcement Feed (F001.1): Create a dedicated feed or section where important announcements and updates are displayed.

- [x] Filter by Branch (F001.2): Filter announcements by user’s branch, showing announcements meant for the branch user is currently in.

**Comment by ishreya09** [comment]
@DarkKnightSgh testing assigned

**Comment by DarkKnightSgh** [comment]
<img width="550" alt="Screenshot 2023-11-17 at 8 51 02 AM" src="https://github.com/ishreya09/Campus-Compass/assets/106529095/64c7d0c4-2416-42cf-a743-112ac054d6f7">
