### ISSUE TITLE
US023 - As a user, I want to access a comprehensive profile page that allows me to view all my authored posts, uploaded resources, and the clubs I am a part of.

### ISSUE THREAD

**Issue by ishreya09** [ishreya09/Campus-Compass#23]
- [x] Posts Listing (F001): Display a list of all posts authored by the user within their profile.

- [x] Resources Listing (F002): Present a list of all resources uploaded by the user in their profile.

- [x] Club Membership Display (F003): Show the clubs or groups the user is a member of in their profile.

**Comment by Mystery510** [comment]
@DarkKnightSgh testing
