### ISSUE TITLE
US024- As a user, I want the ability to view other users' profile pages, where I can access their basic information, initiate a chat with them, and browse the posts and resources they have shared.

### ISSUE THREAD

**Issue by ishreya09** [ishreya09/Campus-Compass#24]
- [x] User Profile Access (F001): Enable users to access the profile page of other users based on usernames.

- [x] Basic Information Display (F002): Present the basic information of the viewed user, including their name, bio, and other relevant details.

- [x] Chat Option (F003): Implement a chat or messaging feature that allows users to initiate a conversation with the viewed user through WhatsApp API. Ensure this button is shown only when user has permitted access to show number publicly.

- [x] Posts and Resources Listing (F004): Display a list of the posts and resources shared by the viewed user.

**Comment by Mystery510** [comment]
@Shreyatippireddy testing
