### ISSUE TITLE
US025- As a user, I want access to a search functionality that allows me to efficiently search for posts, resources, announcements, and users within the platform.

### ISSUE THREAD

**Issue by ishreya09** [ishreya09/Campus-Compass#25]
- [x] Global Search Bar (F001): Implement a search bar accessible from any page within the platform.

- [x] Posts Search (F002): Enable users to search for posts based on keywords, titles, or tags.

- [x] Resources Search (F003): Allow users to search for resources by keywords, titles, or tags.

- [x] Announcements Search (F004): Provide a search option for announcements based on keywords or titles.

- [x] Users Search (F005): Enable users to search for other users by name, username, or other identifying information.

- [x] Search Results Page (F006): Present search results in a structured manner for easy user navigation.

**Comment by Mystery510** [comment]
@DarkKnightSgh testing
