### ISSUE TITLE
US003-As a user, I want to register and log in using user-friendly forms.

### ISSUE THREAD

**Issue by ishreya09** [ishreya09/Campus-Compass#3]
- [x] Create Branch and Department models and create API to fetch branch given department_id (F001) 

User Registration (F002): Create user-friendly registration forms to allow new users to sign up for an account. This feature involves:

- [x] Registration Form (F002.1): Design and implement a user registration form with fields such as username, email, password, and any additional user information required.

- [x] User Registration View (F002.2): Create a Django view to handle the registration form submission. This view will validate the data, create a new user account, and store it in the database. 

- [x] User Data Protection (F002.3): Ensure secure user authentication during the registration process. Passwords should be securely hashed before storage and CSRF tokens should be used to avoid CSRF attacks.

User Login (F003): Implement user-friendly login forms for existing users to access their accounts. This feature involves:

- [x] Login Form (F003.1): Design and implement a user login form with fields for username or email and password.

- [x] Login View (F003.2): Create a Django view to handle user login. The view should authenticate users based on their credentials and set up user sessions.

User Logout (F004): Provide users with the ability to log out from their accounts securely. This feature involves:

- [x] Logout View (F004.1): Implement a Django view that handles user logout. This view should invalidate the user's session.

**Comment by ishreya09** [comment]
@Shreyatippireddy testing pending

**Comment by DarkKnightSgh** [comment]
<img width="612" alt="Screenshot 2023-11-16 at 2 48 45 PM" src="https://github.com/ishreya09/Campus-Compass/assets/106529095/c4a6f40a-2c9d-4209-b972-19b44b70991d">
